#lang typed/racket/base

;; This is an internal version string.  It should have no external meaning.
;; This file is touched by "bump.version.rkt": do not edit this file manually unless
;; you really know what you're doing.

(provide version)
(: version String)

(define version "1.133")
