all:
	../whalesong get-runtime  >runtime.js
	../whalesong get-javascript talk.rkt >talk.js
#	../whalesong get-javascript --compress-javascript rain.rkt >rain.js
#	../whalesong get-javascript --compress-javascript pacman.rkt >pacman.js
#	../whalesong get-javascript --compress-javascript hello.rkt >hello.js
#	../whalesong get-javascript --compress-javascript fact.rkt > fact.js
