#lang planet dyoo/whalesong/base

(substring "hello world" 0)
(substring "hello world" 1)
(substring "hello world" 2)
(substring "hello world" 3)
(substring "hello world" 0)
(substring "hello world" 1 1)
(substring "hello world" 1 2)
(substring "hello world" 1 3)
(substring "hello world" 2 2)
(substring "hello world" 2 3)
(substring "hello world" 3 3)
(substring "hello world" 3 4)
(substring "hello world" 3 5)

(string-copy "hello world")


(list->string '())
(list->string '(#\h #\e #\l #\l #\o))


(string)
(string #\a #\b #\c)

(string-ref "hello" 0)
(string-ref "hello" 1)
(string-ref "hello" 2)
(string-ref "hello" 4)

(string->list "xyz")
(string->list "x")
(string->list "")

(string<? "" "")
(string<? "hello" "Hello")
(string<? "hello" "hello")
(string<? "hello" "hi")
(string<? "hello" "he")
(string<? "a" "a")
(string<? "a" "b")
(string<? "b" "a")
(string<? "b" "b")
(string<? "ba" "ab")
(string<? "ba" "baa")
(string<? "baaa" "baa")

(string<=? "" "")
(string<=? "hello" "Hello")
(string<=? "hello" "hello")
(string<=? "hello" "hi")
(string<=? "hello" "he")
(string<=? "a" "a")
(string<=? "a" "b")
(string<=? "b" "a")
(string<=? "b" "b")
(string<=? "ba" "ab")
(string<=? "ba" "baa")
(string<=? "baaa" "baa")

(string>? "" "")
(string>? "hello" "Hello")
(string>? "hello" "hello")
(string>? "hello" "hi")
(string>? "hello" "he")
(string>? "a" "a")
(string>? "a" "b")
(string>? "b" "a")
(string>? "b" "b")
(string>? "ba" "ab")
(string>? "ba" "baa")
(string>? "baaa" "baa")

(string>=? "" "")
(string>=? "hello" "Hello")
(string>=? "hello" "hello")
(string>=? "hello" "hi")
(string>=? "hello" "he")
(string>=? "a" "a")
(string>=? "a" "b")
(string>=? "b" "a")
(string>=? "b" "b")
(string>=? "ba" "ab")
(string>=? "ba" "baa")
(string>=? "baaa" "baa")

(string=? "" "")
(string=? "hello" "Hello")
(string=? "hello" "hello")
(string=? "hello" "hi")
(string=? "hello" "he")
(string=? "a" "a")
(string=? "a" "b")
(string=? "b" "a")
(string=? "b" "b")
(string=? "ba" "ab")
(string=? "ba" "baa")
(string=? "baaa" "baa")








(string-ci<? "" "")
(string-ci<? "hello" "Hello")
(string-ci<? "hello" "hello")
(string-ci<? "hello" "hi")
(string-ci<? "hello" "he")
(string-ci<? "a" "a")
(string-ci<? "a" "b")
(string-ci<? "b" "a")
(string-ci<? "b" "b")
(string-ci<? "ba" "ab")
(string-ci<? "ba" "baa")
(string-ci<? "baaa" "baa")

(string-ci<=? "" "")
(string-ci<=? "hello" "Hello")
(string-ci<=? "hello" "hello")
(string-ci<=? "hello" "hi")
(string-ci<=? "hello" "he")
(string-ci<=? "a" "a")
(string-ci<=? "a" "b")
(string-ci<=? "b" "a")
(string-ci<=? "b" "b")
(string-ci<=? "ba" "ab")
(string-ci<=? "ba" "baa")
(string-ci<=? "baaa" "baa")

(string-ci>? "" "")
(string-ci>? "hello" "Hello")
(string-ci>? "hello" "hello")
(string-ci>? "hello" "hi")
(string-ci>? "hello" "he")
(string-ci>? "a" "a")
(string-ci>? "a" "b")
(string-ci>? "b" "a")
(string-ci>? "b" "b")
(string-ci>? "ba" "ab")
(string-ci>? "ba" "baa")
(string-ci>? "baaa" "baa")

(string-ci>=? "" "")
(string-ci>=? "hello" "Hello")
(string-ci>=? "hello" "hello")
(string-ci>=? "hello" "hi")
(string-ci>=? "hello" "he")
(string-ci>=? "a" "a")
(string-ci>=? "a" "b")
(string-ci>=? "b" "a")
(string-ci>=? "b" "b")
(string-ci>=? "ba" "ab")
(string-ci>=? "ba" "baa")
(string-ci>=? "baaa" "baa")

(string-ci=? "" "")
(string-ci=? "hello" "Hello")
(string-ci=? "hello" "hello")
(string-ci=? "hello" "hi")
(string-ci=? "hello" "he")
(string-ci=? "a" "a")
(string-ci=? "a" "b")
(string-ci=? "b" "a")
(string-ci=? "b" "b")
(string-ci=? "ba" "ab")
(string-ci=? "ba" "baa")
(string-ci=? "baaa" "baa")

#"hello"
